version: "4"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: crud_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3306:3306"
    volumes:
      - "./database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin1234
      - DB_DATABASE=crud_db
    depends_on:
      - db
