name: Deploy nodejs apps to local vm

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Deploy apps
        run: |
          docker compose pull
          docker compose down
          docker compose up -d --build
